#passpwrd root encoded to uHiKOtpKgrNmsVNbtiYS2g==
spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: uHiKOtpKgrNmsVNbtiYS2g==
      database: db_test
      port: 27017
      host: localhost
